applications:
  operator:

    stack: ["cowsay"]

    web:
      commands:
        start: sleep infinity

      locations:
        "/":
          root: ""
          passthru: true

        # Disable server-side scripts
          scripts: false
