
applications:
  operator:

    source:
      root: "/"
    type: "nodejs:20"

    web:
      commands:
        start: sleep infinity        
      locations:
        "/":
          root: ""
          passthru: true
        # Disable server-side scripts
          scripts: false